### ISSUE TITLE
 Abnormal reproduction results

### ISSUE THREAD

**Issue by lyr5333** [IntelligentDDS/Nezha#1]

**Comment by phamquiluan** [comment]
Even though, I don't know why you updated the issue and closed it but... I encountered this issue and obtained exactly these numbers.

![image](https://github.com/IntelligentDDS/Nezha/assets/24642166/abde7313-bac0-4a5d-bcf5-fd89ffd4cd4d)


![image](https://github.com/IntelligentDDS/Nezha/assets/24642166/1ad72845-78ad-4024-bc50-5731a4f5e8b7)

**Comment by phamquiluan** [comment]
@lyr5333 are you able to reproduce the reported results yet?

**Comment by molujia** [comment]
> @lyr5333 are you able to reproduce the reported results yet?

I'd like to know how do you built your environment according to the "requirement.txt". I've met some dependency problems, which is about "Orange3_Associate==1.1.9". 
Following the "Readme.md" and I can not build environment successfully. And I've managed to build my own environment by using pypi. In this way, the environment was built, but the outcome was terrible. :(
