### ISSUE TITLE
About Nezhe, beseek help

### ISSUE THREAD

**Issue by molujia** [IntelligentDDS/Nezha#2]
Greetings.
First of all, I sincerely appreciate your generosity in providing the source code.
We plan to use Nezha as part of the baseline of our new platform, for which I need to reproduce Nezhe on five  multi-modal datasets.
In this process, I've met two problem and had some tiny questions about Nezha.
The first problem is about the test environment.  In requirements.txt, Orange3_Associate==1.1.9 was in demand, which also requires numpy==1.15.4. But Orange3_Associate1.1.9 requires Orange3>=3.25.0 and openTSNE>=0.6.1, which two requires numpy>=1.16.0.
The second problem may be caused by the first one: I've successfully run Nezha with Orange3_Associate==1.1.9 and numpy==1.15.4 on python3.6. But the outcome was awful. Here's part of the result:
[INFO]2023-11-13 21:04:39,357 pattern_ranker.py:650: --------AS@1 Result-------
[INFO]2023-11-13 21:04:39,357 pattern_ranker.py:651: 5.357143 %
[INFO]2023-11-13 21:04:39,357 pattern_ranker.py:652: --------AS@3 Result-------
[INFO]2023-11-13 21:04:39,357 pattern_ranker.py:653: 7.142857 %
[INFO]2023-11-13 21:04:39,357 pattern_ranker.py:654: --------AS@5 Result-------
[INFO]2023-11-13 21:04:39,357 pattern_ranker.py:655: 7.142857 %
I'd like to know what caused this.
And I noticed that your source code provide your own data, which contains both trace_id file and trace file. If my understanding was correct, the code only use traces when its id appreared in the trace_id file (reflected in data_integrate.py and in the function data_integrate()). I wonder why.
Please provide illuminate and dispell the darkness for us, amen.

**Comment by phamquiluan** [comment]
are you able to reproduce the results yet, bro @molujia =))

**Comment by molujia** [comment]
tomorrow I will help you. But today I have other job to do. :)



---Original---
From: "Luan ***@***.***&gt;
Date: Thu, Nov 16, 2023 22:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [IntelligentDDS/Nezha] About Nezhe, beseek help (Issue #2)




 
are you able to reproduce the results yet, bro @molujia =))

**Comment by yuxiaoba** [comment]
Thanks you feed back. I will try to reproduce this bug  in a new server and fix it in next week.

**Comment by yuxiaoba** [comment]
Hi, @molujia , I have update the requirement  file and test Nezha in a new server. I got the consistent result with the previous result. 

![image](https://github.com/IntelligentDDS/Nezha/assets/35029651/f749b9c7-9c35-489b-a93f-6b3baae3ff2d)

Can you try it again?

**Comment by molujia** [comment]
> Hi, @molujia , I have update the requirement file and test Nezha in a new server. I got the consistent result with the previous result.
> 
> ![image](https://user-images.githubusercontent.com/35029651/283637753-f749b9c7-9c35-489b-a93f-6b3baae3ff2d.png)
> 
> Can you try it again?

With pleasure.
