### ISSUE TITLE
Reproducibility matter

### ISSUE THREAD

**Issue by phamquiluan** [IntelligentDDS/Nezha#3]
Hi my idol @yuxiaoba :smile: 

I've been trying to reproduce the results of Nezha on Hister shop. I followed the instructions carefully to install the environment, but unable to reproduce the results. I have attached here the results I got.

![image](https://github.com/IntelligentDDS/Nezha/assets/24642166/a9faa46f-a7a5-4629-9d88-9e491f3694e3)

I see other people also have the number exactly like me (https://github.com/IntelligentDDS/Nezha/issues/1)

I'm wondering whether you have met this problem before (and how did you solve it?). I know you're busy, but please help when you have time. Much appreciate! :smile:

**Comment by yuxiaoba** [comment]
Hi luan, thanks you feed back. I will try to reproduce this bug  in a new server and fix it in next week.

**Comment by yuxiaoba** [comment]
Hi, luan, I have update code and test it in a new server. I get the consistent result with our previous reuslt. 

![image](https://github.com/IntelligentDDS/Nezha/assets/35029651/6e890ad1-65e3-4bd4-bef0-3fcbc306477b)

Can you show more log information in running phase?

**Comment by molujia** [comment]
> Hi my idol @yuxiaoba 😄
> 
> I've been trying to reproduce the results of Nezha on Hister shop. I followed the instructions carefully to install the environment, but unable to reproduce the results. I have attached here the results I got.
> 
> ![image](https://user-images.githubusercontent.com/24642166/283138100-a9faa46f-a7a5-4629-9d88-9e491f3694e3.png)
> 
> I see other people also have the number exactly like me (#1)
> 
> I'm wondering whether you have met this problem before (and how did you solve it?). I know you're busy, but please help when you have time. Much appreciate! 😄

I've tried on two different  operating systems. Make sure your environment was built on Linux, cause on Windows even the same environment may have weired mistake.
And here's my environment's requirements:
cachetools (4.2.1)
certifi (2021.5.30)
colorama (0.4.5)
cycler (0.11.0)
drain3 (0.9.10)
importlib-metadata (4.8.3)
importlib-resources (5.4.0)
jsonpickle (1.5.1)
kiwisolver (1.3.1)
matplotlib (3.3.4)
more-itertools (8.12.0)
numpy (1.19.5)
Orange3-Associate (1.1.0)
pandas (0.23.4)
Pillow (8.4.0)
pip (9.0.1)
psutil (5.9.0)
pyfpgrowth (1.0)
pyparsing (3.1.1)
python-dateutil (2.8.2)
pytz (2023.3.post1)
PyYAML (6.0)
scipy (1.5.4)
setuptools (58.0.4)
six (1.16.0)
spmf (1.4)
tqdm (4.64.1)
treelib (1.7.0)
typing-extensions (4.1.1)
wheel (0.37.1)
wincertstore (0.2)
zipp (3.6.0)
Notice that the Orange3-Associate was not the same version which "requirements.txt" required.
I hope this will help you. Amen.

**Comment by phamquiluan** [comment]
Thank you so much for your help @yuxiaoba :D 

I'm able to reproduce it using python3.6

**Comment by udi-aharon** [comment]
For python 3.10, update the "get_netwrok_metric" function to fix the issue:

```

def get_netwrok_metric(trace_file, pod_name):
    """
    func get_netwrok_metric: use trace data to get netwrok metric
        :parameter
        time - to regex timestamp e.g, "2022-04-18 13:00"
        data_dir
        pod_name
        :return
        p90 netwrok latency
    """
    pod_name = pod_name.strip().lower()
    latency_list = []

    if "front" in pod_name:
        # front end dose not calculate netwrok latency
        return 10, 10

    df = pd.read_csv(trace_file, usecols=['TraceID', 'SpanID', 'ParentID', 'PodName', 'EndTimeUnixNano'])
    df['PodName'] = df['PodName'].str.strip().str.lower()
    pod_reader = df.set_index('PodName')
    parent_span_reader = df.set_index('SpanID')

    try:
        pod_spans = pod_reader.loc[[pod_name], [
            'SpanID', 'ParentID', 'EndTimeUnixNano']]
    except Exception as e:
        service = pod_name.rsplit('-', 1)[0]
        service = service.rsplit('-', 1)[0]

        csv_file = dirname(__file__) +  "/metric_threshold/" + service + ".csv"
        pod_reader = pd.read_csv(csv_file, usecols=['NetworkP90(ms)'])
        # print("pod", pod_name, " not found in trace, return default ",
        #       float(pod_reader.iloc[0]))
        logger.info(f"pod: {pod_name} not found in trace, return default: {float(pod_reader.iloc[0].item()), 0}")

        return float(pod_reader.iloc[0].item()), 0
    
    if len(pod_spans['SpanID']) > 0:
        # process span independentlt and order by timestamp
        for span_index in range(len(pod_spans['SpanID'])):
            # span event
            parent_id = pod_spans['ParentID'].iloc[span_index]
            pod_start_time = int(
                pod_spans['EndTimeUnixNano'].iloc[span_index])
            try:
                parent_pod_span = parent_span_reader.loc[[
                    parent_id], ['PodName', 'EndTimeUnixNano']]
                if len(parent_pod_span) > 0:
                    for parent_span_index in range(len(parent_pod_span['PodName'])):
                        parent_pod_name = parent_pod_span['PodName'].iloc[parent_span_index]
                        parent_end_time = int(
                            parent_pod_span['EndTimeUnixNano'].iloc[parent_span_index])

                    if str(parent_pod_name) != str(pod_name):
                        latency = (parent_end_time - pod_start_time) / \
                            1000000  # convert to microsecond
                        # if "contacts-service" in pod_name:
                        #     logger.info("%s, %s, %s, %s, %s" % (
                        #         pod_name, pod_spans['SpanID'].iloc[span_index], parent_pod_name, pod_spans['ParentID'].iloc[span_index], latency))
                        latency_list.append(latency)
            except Exception as e:
                logger.error(f"Parent span ID {parent_id} not found: {e}")
                pass
    #logger.info("%s latency is %s" %(pod_name, np.percentile(latency_list, 90)))
    if len(latency_list) > 2:
        return np.nanpercentile(latency_list, 90), statistics.stdev(latency_list)
    else:
        return 10, 10

```
