### ISSUE TITLE
How did you come up with the current Drain config?

### ISSUE THREAD

**Issue by phamquiluan** [IntelligentDDS/Nezha#4]
Hi my idol @yuxiaoba 😄

I came across the Drain config and really interested in it. How did you obtain these numbers and regular expressions?
https://github.com/IntelligentDDS/Nezha/blob/main/log_template/drain3_hipster.ini

Thank you so much in advance ^^

**Comment by yuxiaoba** [comment]
There are some regular expressions that came up from looking at the logs.  

You can also use other log parsing approaches that do not rely on regular expressions.

**Comment by phamquiluan** [comment]
Thank you so much, much appreciated <3 @yuxiaoba!
