### ISSUE TITLE
MicroRCA and TraceAnomaly implementations

### ISSUE THREAD

**Issue by MaxiStefan** [IntelligentDDS/Nezha#5]
Hi,

I have gone through your paper and published code here on GitHub and I was wondering if you've made public the way you implemented MicroRCA and TraceAnomaly for the comparison with Nezha.

I inspected the available code here but I don't think I've seen their usage.

Thanks in advance!

**Comment by yuxiaoba** [comment]
Hello, 

The code of microrca is available  at https://github.com/elastisys/MicroRCA

And the code of TraceAnomaly is available  at https://github.com/NetManAIOps/TraceAnomaly
